# Site settings
title: Ryan Glassett
email: your-email@example.com
description: >-
  Software Engineer at Enjoy Technology. Fluent in Ruby, PostgreSQL, and
  JavaScript. Conversant in Spanish and Mandarin.
baseurl: ""
url: "https://rglassett.github.io"
google_analytics: UA-119864225-1

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude from processing.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
